# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "loop_wrapper"
version = "3.2.0"
description = "loop_wrapper is a job-control tool to make it easier to loop through datetime ranges"
readme = "README.md"
requires-python = ">=3.6"
license = "GPL-2.0-only"
keywords = ["loop", "datetime", "job-control"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

authors = [
  { name="Thomas Lavergne", email="thomasl@met.no" },
  { name="Mathew Duggan", email="mat@matduggan.com" },
]

dependencies = [
  "python-dateutil>=2.9.0",
]

[project.urls]
homepage = "https://github.com/metno/loop_wrapper"
"Bug Tracker" = "https://github.com/metno/loop_wrapper/issues"
documentation = "https://loop_wrapper.readthedocs.io/"
